# Exercises

In [1]:
import numpy as np

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [3]:

# formula = weight / (height**2) * 730
height = [69, 70, 71, 72, 73, 74, 75]
weight = [110, 120, 130, 140, 150, 160, 170]

h1 = np.array(height)
w1 = np.array(weight)

bmi = w1 / (h1**2) * 730
bmi
# OUTPUT: [16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
# 22.06222222]




array([16.86620458, 17.87755102, 18.82562984, 19.71450617, 20.54794521,
       21.32943755, 22.06222222])

### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [14]:
np.random.uniform(3,10,(3,3))

# def random_matrix(a,b):
#     rando = np.random.uniform(a,b,(3,3))
#     return rando(a,b)

# print(random_matrix(1,5))

# """
# Example Result for make_matrix(0,15,(3,3)):
# array([[14.21633515,  7.98846653,  9.64140715],
#        [ 6.30982234,  9.96414331,  8.43153688],
#        [14.73102068, 11.76072894, 14.23356121]])
# """
# # def make_matrix(low,high,shape,data_type = float): -- Example
# #     pass

array([[4.34576434, 6.631822  , 8.25614169],
       [5.17697669, 8.88873476, 9.04638096],
       [3.26854626, 6.84123724, 4.49155984]])

### #3 - Open and load the data for the Chicago White Sox hitting data for this past season.Create a function that will compare the infield players output vs the outfield players output vs *hybrid. (Infield - {C, 1B, 2B, SS, 3B, MI}, Outfield - {LF, CF, RF, OF}, *Hybrid - {DH, UT}) for a specific stat. i.e. BA or HR or OPS

*Hybrid is optional


In [26]:
import csv
import numpy as np


FIELDS = ['Rank', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rank', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

def load_data(filename, d=''):
    data = np.genfromtxt(filename, dtype=DATATYPES, delimiter=d, names=True, invalid_raise=False)
    return data
    
    
whitesox = load_data('whitesox_hitting.txt')
whitesox
# names = whitesox['Name']
# print(names)

#Test to make sure you have the correct data



<ipython-input-26-e5b35e4ae5cd>:14: ConversionWarning: Some errors were detected !
    Line #2 (got 29 columns instead of 28)
    Line #3 (got 29 columns instead of 28)
    Line #4 (got 29 columns instead of 28)
    Line #5 (got 29 columns instead of 28)
    Line #6 (got 29 columns instead of 28)
    Line #7 (got 29 columns instead of 28)
    Line #8 (got 29 columns instead of 28)
    Line #9 (got 29 columns instead of 28)
    Line #10 (got 29 columns instead of 28)
    Line #11 (got 29 columns instead of 28)
    Line #12 (got 29 columns instead of 28)
    Line #13 (got 29 columns instead of 28)
    Line #14 (got 29 columns instead of 28)
    Line #15 (got 29 columns instead of 28)
    Line #16 (got 29 columns instead of 28)
    Line #17 (got 29 columns instead of 28)
    Line #18 (got 29 columns instead of 28)
    Line #19 (got 29 columns instead of 28)
    Line #20 (got 29 columns instead of 28)
    Line #21 (got 29 columns instead of 28)
    Line #22 (got 29 columns instead of 28)
 

array([],
      dtype=[('Rk', '<i4'), ('Pos', 'S25'), ('Name', 'S25'), ('Age', '<i4'), ('G', '<i4'), ('PA', '<i4'), ('AB', '<i4'), ('R', '<i4'), ('H', '<i4'), ('2B', '<i4'), ('3B', '<i4'), ('HR', '<i4'), ('RBI', '<i4'), ('SB', '<i4'), ('CS', '<i4'), ('BB', '<i4'), ('SO', '<i4'), ('BA', '<f4'), ('OBP', '<f4'), ('SLG', '<f4'), ('OPS', '<f4'), ('OPS_1', '<i4'), ('TB', '<i4'), ('GDP', '<i4'), ('HBP', '<i4'), ('SH', '<i4'), ('SF', '<i4'), ('IBB', '<i4')])

In [27]:


FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

#Use this function to actually open the data inside of a NDArray
def load_data(filename, d=''):
    data = np.genfromtxt(filename, dtype=DATATYPES, delimiter=d, names=True, invalid_raise=False)
    return data
    
    
whitesox = load_data('whitesox_hitting.txt')
whitesox


<ipython-input-27-938ea1230941>:11: ConversionWarning: Some errors were detected !
    Line #2 (got 29 columns instead of 28)
    Line #3 (got 29 columns instead of 28)
    Line #4 (got 29 columns instead of 28)
    Line #5 (got 29 columns instead of 28)
    Line #6 (got 29 columns instead of 28)
    Line #7 (got 29 columns instead of 28)
    Line #8 (got 29 columns instead of 28)
    Line #9 (got 29 columns instead of 28)
    Line #10 (got 29 columns instead of 28)
    Line #11 (got 29 columns instead of 28)
    Line #12 (got 29 columns instead of 28)
    Line #13 (got 29 columns instead of 28)
    Line #14 (got 29 columns instead of 28)
    Line #15 (got 29 columns instead of 28)
    Line #16 (got 29 columns instead of 28)
    Line #17 (got 29 columns instead of 28)
    Line #18 (got 29 columns instead of 28)
    Line #19 (got 29 columns instead of 28)
    Line #20 (got 29 columns instead of 28)
    Line #21 (got 29 columns instead of 28)
    Line #22 (got 29 columns instead of 28)
 

array([],
      dtype=[('Rk', '<i4'), ('Pos', 'S25'), ('Name', 'S25'), ('Age', '<i4'), ('G', '<i4'), ('PA', '<i4'), ('AB', '<i4'), ('R', '<i4'), ('H', '<i4'), ('2B', '<i4'), ('3B', '<i4'), ('HR', '<i4'), ('RBI', '<i4'), ('SB', '<i4'), ('CS', '<i4'), ('BB', '<i4'), ('SO', '<i4'), ('BA', '<f4'), ('OBP', '<f4'), ('SLG', '<f4'), ('OPS', '<f4'), ('OPS_1', '<i4'), ('TB', '<i4'), ('GDP', '<i4'), ('HBP', '<i4'), ('SH', '<i4'), ('SF', '<i4'), ('IBB', '<i4')])